### ISSUE TITLE
Build without Linux subsystem?

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [libsdl-org/SDL_rtf#10]
Hi team
Is there a way to build this library on Win-64 without using a Linux subsystem (bash sh)?
Is there a way with MinGW-64 mingw32-make or CMake?

Best regards
Axle

**Comment by madebr** [comment]
Both SDL2_rtf and SDL3_rtf git can be built with CMake.
It does not depend on unix-like utils (such as pkg-config).

Don't use [the old 0.1.0 release](https://www.libsdl.org/projects/SDL_rtf/release/).
