### ISSUE TITLE
Build with CMake gives multiple errors.

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [libsdl-org/SDL_rtf#11]
Hi team
I have been trying to build this library for several hours. I am a bit new to CMake. I cant find the correct flags to set, and keep getting errors.
```
CMake Error at CMakeLists.txt:15 (message):
  Prevented in-tree built.  Please create a build directory outside of the
  SDL_rtf source code and call cmake from there

-- Configuring incomplete, errors occurred!
```
This is why I thought I had to sh ./configure
>
I am setting paths manually with SET from the CMD promp and pointing cmake at the gcc g++ compilers
```
SET PATH=%PATH%;C:\Dev-Cpp-Emb_Winlibs\TDM-GCC-64\bin;C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL_rtf-SDL2
cmake -DCMAKE_C_COMPILER=C:/Dev-Cpp-Emb_Winlibs/TDM-GCC-64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/Dev-Cpp-Emb_Winlibs/TDM-GCC-64/bin/g++.exe C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL_rtf-SDL2
```
I am getting the CMakeCache.txt file being generated but no further.
Regard
Axle

**Comment by Axle-Ozz-i-sofT** [comment]
Sorry if I am asking in the wrong place. I will move my questions to the forum.
My bad...

**Comment by madebr** [comment]
The error message explains what you're doing wrong:
```
  Prevented in-tree built.  Please create a build directory outside of the
  SDL_rtf source code and call cmake from there
```

You cannot configure in the source folder. Create a build folder for this.
`cd` to this build folder, and run `cmake relative/path/to/SDL_rtf`.

**Comment by Axle-Ozz-i-sofT** [comment]
This is what I have just tried :(
From both in the source dir as well as from ..\build\build.cmd
I also set the path to the build directory and the source directory
`SET PATH=%PATH%;C:\Dev-Cpp-Emb_Winlibs\TDM-GCC-64\bin;C:\Dev-Cpp-Emb_Winlibs\SDL2\Build`
as well as trying
`SET PATH=%PATH%;C:\Dev-Cpp-Emb_Winlibs\TDM-GCC-64\bin;C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL_rtf-SDL2`
>
Maybe the compiler paths are incorrect.
I assumed `-DCMAKE_C_COMPILER=` to be a generic VALUE for CMake. I will remove and try again, but previously CMake defaults to the MS compiler instead of GCC

**Comment by Axle-Ozz-i-sofT** [comment]
OK, had to remove the previous cache files.
Still missing something though...
tree:
SDL2
--SDL2\build\build.cmd
--SDL2\SDL_rtf-SDL2\*.c;*.h


```
C:\Dev-Cpp-Emb_Winlibs\SDL2\Build>cmake  -G "MinGW Makefiles" -DCMAKE_C_COMPILER=C:/Dev-Cpp-Emb
cc.exe -DCMAKE_CXX_COMPILER=C:/Dev-Cpp-Emb_Winlibs/TDM-GCC-64/bin/g++.exe C:\Dev-Cpp-Emb_Winlib
-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Dev-Cpp-Emb_Winlibs/TDM-GCC-64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring SDL2_rtf 2.0.0
-- Using private SDL2 find module
CMake Error at cmake/PrivateSdlFunctions.cmake:63 (find_package):
  By not providing "FindPrivateSDL2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PrivateSDL2", but CMake did not find one.

  Could not find a package configuration file provided by "PrivateSDL2"
  (requested version 2.0.0) with any of the following names:

    PrivateSDL2Config.cmake
    privatesdl2-config.cmake

  Add the installation prefix of "PrivateSDL2" to CMAKE_PREFIX_PATH or set
  "PrivateSDL2_DIR" to a directory containing one of the above files.  If
  "PrivateSDL2" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:69 (sdl_find_sdl2)

-- Configuring incomplete, errors occurred!
```

**Comment by Axle-Ozz-i-sofT** [comment]
Depends on SDL2.dll :/

**Comment by madebr** [comment]
You need SDL2 and SDL2_ttf for SDL2_rtf.
So download/build those before.
Use [`-DCMAKE_PREFIX_PATH=...`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html) to inform CMake about the location of the dependencies.

**Comment by Axle-Ozz-i-sofT** [comment]
OK, got a successful build. So all good :)
Yes, I just realized I didn't put the 2 above depends paths into the batch file.
showrtf.exe runs and asks for a *.ttf so All good.

Thank you very much for the assist, even if it was a bit of a rubber duck moment lol
I am still a bit green with this cmake stuff lol
kind regards
Axle

**Comment by Axle-Ozz-i-sofT** [comment]
P.S. in my case it ended up being build.cmd:
```
SET PATH=%PATH%;C:\Dev-Cpp-Emb_Winlibs\TDM-GCC-64\bin;C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL2-2.30.0\x86_64-w64-mingw32\include\SDL2;C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL2-2.30.0\x86_64-w64-mingw32\bin;C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL_rtf-SDL2
cmake  -G "MinGW Makefiles" -DCMAKE_C_COMPILER=C:/Dev-Cpp-Emb_Winlibs/TDM-GCC-64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/Dev-Cpp-Emb_Winlibs/TDM-GCC-64/bin/g++.exe C:\Dev-Cpp-Emb_Winlibs\SDL2\SDL_rtf-SDL2
mingw32-make
PAUSE
```
