### ISSUE TITLE
The program hangs

### ISSUE THREAD

**Issue by WLD-Graphic** [libsdl-org/SDL_rtf#4]
Are there any samples or example codes that I can follow? I tried to run the following code:-

    RTF_FontEngine fontEngine;
    RTF_Context *ctx = RTF_CreateContext(renderer, &fontEngine);

    RTF_Load(ctx, "Document.rtf");

The program froze and became unresponsive. I compiled it in both MSVC++ and MinGW, the result is the same.

Am I doing something wrong or does the library needs to be updated...

**Comment by sezero** [comment]
The showrtf example program works fine and should be a good guide:
https://github.com/libsdl-org/SDL_rtf/blob/main/showrtf.c

**Comment by slouken** [comment]
Go ahead and attach a link to the document that is freezing as well, there might be another bug there.

**Comment by WLD-Graphic** [comment]
Thank you, everybody.

After I checked the code in **showrtf.c**, I realized where I missed. My application works now. It looks like it reads text only from the RTF document, it does not read the embedded images.

This issue can be closed now.

**Comment by sezero** [comment]
OK then.
